### ISSUE TITLE
 direct log In to moodle at the same time as Wordpress

### ISSUE THREAD

**Issue by romain8409** [frumbert/wp2moodle#3]
Hello,

I am in the process of setting up a connection gateway between a wordpress and a moodle for students.

Here is the goal of the project:
- students connect to a wordpress portal and, on this portal, there are links to the different pages of an associated moodle such as the schedule, the course lists, etc.
- The goal is that when the students arrive on the moodle by links, they are automatically authenticated on the Moodle and access the requested page.

I tried your plugin and it works very well for authentication if you add the shortcode to a page and click on the link.

On the other hand, do you think it is possible to execute the shortcode at the time of connection to Wordpress or even to perform identification on the moodle at the time of connection to the Wordpress portal?

Currently, the links to the moodle on the wordpress portal do not work until you click on the link generated by the shortcode. On the other hand, once you are logged into the moodle, you can access the direct links on the portal by being automatically identified on moodle.

In advance, thank you for your answer.

**Comment by frumbert** [comment]
This plugin was designed to work at the time the user clicks the link, rather than operating on a schedule. Other plugins such as https://edwiser.org/bridge/ are out there for catering for that need.

You can specify the url to override after authentication in the shortcode. e.g.

[wp2moodle course=abc123 url=/mod/page/view.php?id=4325]Open the page[/wp2moodle]
