### ISSUE TITLE
Error writing to database when clicking the shortcode link

### ISSUE THREAD

**Issue by raramuridesign** [frumbert/wp2moodle#5]
Hi @frumbert ,
we are getting this error when the user uses the shortlink.

Error writing to database
More information about this error

Points to this moodle link
https://docs.moodle.org/39/en/error/moodle/dmlwriteexception

Any insight how to solve this would be appreciated
M.

**Comment by raramuridesign** [comment]
@frumbert 
so the issue here is the following

When we have a database of users who have NOT been linked to wp2moodle these users do not have the **ID number**
So - when a user logs in using the new button generated by the short code, the login process will do one of two things

- Give the error about writing to the database or
- Create a duplicate user as mentioned in #4 

In order to fix this, the user id needs to be added to moodle **ID number** field along with the pre-defined prefix from the settings of the plugin.

We are now writing a script which will do the following

- Create a list of all users in Wordpress (id, name, email, reg date etc)
- Attach to this list a match by users email from moodle (id, email, name, surname, ID number, reg date)
- This will also give us duplicates in the system (by date or id)
- We can then build in a sync options to update the ID number

Hope this helps anyone else out there with the same issue.
M

**Comment by frumbert** [comment]
I'll have to update the documentation about this. When initially designed it was assumed that the users would not initially exist in the moodle site and that the idnumber field wouldn't be a problem (since you would be creating the user anyway). Matching existing users on both ends with various fields wasn't in the design spec - being able to specify which field the user gets matched on would be a better idea.

**Comment by raramuridesign** [comment]
@frumbert Initially saw how you did this, I guess when you have existing sites and data this will always be an issue.
Thanks for getting this sorted.
