### ISSUE TITLE
cmid is not working

### ISSUE THREAD

**Issue by nikhil97557** [frumbert/wp2moodle#9]
[wp2moodle class='css-classname' group='group1' cohort='class1' target='_blank' authtext='Please log on' course='TCPR34' cmid='1887']launch the course act[/wp2moodle]

i am using this shortcode to redirect to moodle activity direct using the wordpress link where 1887 is activity id and TCPR34 is my course idnumber, but it is not working. can you please help me?

**Comment by linuxbean001** [comment]
I am also facing the same issue, please let me know the solution.

**Comment by frumbert** [comment]
It might be that the course cannot be found and therefore the cmid value can't be calculated - I was able to replicate this scenario at least. I've put in a [patch](https://github.com/frumbert/wp2moodle/commit/c67069d9d051bd48e8a630ec35ea6723b2f68cec) so that if the courseId isn't matched the course is looked up from the cmid and the code then allows the logon and opens that activity. Check to see if this works

**Comment by frumbert** [comment]
Haven't heard back, or been able to recreate.
